Repository adaapp/testing-dec2021-team3, pull requests merged in 2022-01, with the labels that each got.

#18 Implemented keyboard design and keys
  public/index.html
  public/logo.svg
  public/notecircle.svg
  public/polygon.svg
  public/triangle.svg
  public/tricircle.svg
  src/App.css
  src/App.js
  src/index.css
Labels: enhancement, UI Design

#24 Added splash screen, metronome and volume control
  public/favicon.ico
  public/fonts/MaterialIconsRound-Regular.otf
  public/index.html
  public/svg/logo.svg
  public/svg/metronome.svg
  public/svg/notecircle.svg
  public/svg/polygon.svg
  public/svg/triangle.svg
  public/svg/tricircle.svg
  src/App.css
  src/App.js
  src/metronome.mp3
Labels: enhancement, UI Design

#28 Included CSS for each individual component
  src/components/keyboard/keyboard.css
  src/components/keyboard/keyboard.js
  src/components/splash/splash.css
  src/routes/App.css
Labels: enhancement

#29 Fixed black key linear-gradient when clicked
  src/components/keyboard/keyboard.css
  src/components/keyboard/keyboard.js
Labels: enhancement

#30 Added unit tests for the Splash component
  src/components/splash/splash.js
  src/components/splash/splash.test.js
  src/routes/App.test.js
Labels: testing

#31 Initial tests for the Metronome component
  src/components/metronome/metronome.js
  src/components/metronome/metronome.test.js
Labels: testing

#32 Added GitHub Action for tests, improved App.js tests
  .github/workflows/node.js.yml
  public/design 1.png
  public/design 2.png
  src/components/keyboard/keyboard.js
  src/components/keyboard/keyboard.test.js
  src/components/volume/volume.test.js
  src/routes/App.js
  src/routes/App.test.js
  testing/Manual Test Cases.xlsx
Labels: testing

#33 Added more tests to the Keyboard and App.js, hit 70% coverage
  package.json
  src/components/keyboard/keyboard.js
  src/components/keyboard/keyboard.test.js
  src/components/volume/volume.js
  src/components/volume/volume.test.js
  src/routes/App.js
  src/routes/App.test.js
Labels: testing

#35 Redesigned Splash screen with helper text, based on user feedback
  public/piano.png
  src/components/splash/splash.css
  src/components/splash/splash.js
  src/components/splash/splash.test.js
Labels: enhancement

#37 Added coveralls upload for code coverage (GitHub Action)
  .github/workflows/node.js.yml
Labels: testing

#38 Added a set of testable helper functions
  src/components/keyboard/keyboard.js
  src/components/metronome/metronome.js
  src/helpers.js
  src/helpers.test.js
Labels: enhancement, testing

#39 Added logic tests for each helper function, bubble shows converted note
  src/components/keyboard/keyboard.js
  src/components/metronome/metronome.js
  src/components/metronome/metronome.test.js
  src/components/volume/volume.js
  src/components/volume/volume.test.js
  src/helpers.js
  src/helpers.test.js
  src/routes/App.js
  src/routes/App.test.js
  src/smoke.test.js
Labels: enhancement, testing

#41 Add comments to the helper functions, App.js and the Volume component
  src/components/volume/volume.js
  src/helpers.js
  src/routes/App.js
Labels: enhancement

#42 Obtained 100% code coverage. Our lives are complete now.
  src/components/keyboard/keyboard.js
  src/components/keyboard/keyboard.test.js
  src/components/metronome/metronome.js
  src/components/metronome/metronome.test.js
  src/components/splash/splash.js
  src/components/splash/splash.test.js
  src/components/volume/volume.test.js
  src/helpers.test.js
  src/routes/App.test.js
Labels: testing

#43 Added regression testing using react-test-renderer
  package-lock.json
  package.json
  src/__snapshots__/regression.spec.js.snap
  src/regression.spec.js
Labels: testing

#44 In-depth E2E testing with Puppeteer, with automated screenshots and a ton of features <3
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  src/__snapshots__/regression.spec.js.snap
  src/components/splash/splash.js
  src/e2e.test.js
  src/routes/App.js
  src/screenshots/bubble/2.png
  src/screenshots/bubble/D.png
  src/screenshots/bubble/a.png
  src/screenshots/bubble/default.png
  src/screenshots/bubble/m.png
  src/screenshots/home.png
  src/screenshots/keys/hover-2.png
  src/screenshots/keys/hover-E.png
  src/screenshots/keys/hover-L.png
  src/screenshots/keys/hover-Q.png
  src/screenshots/keys/hover-a.png
  src/screenshots/keys/hover-m.png
  src/screenshots/keys/pressed-E.png
  src/screenshots/keys/pressed-O.png
  src/screenshots/keys/pressed-V.png
  src/screenshots/metronome/199.png
  src/screenshots/metronome/5.png
  src/screenshots/metronome/502.png
  src/screenshots/metronome/emptyTo1.png
  src/screenshots/metronome/focused.png
  src/screenshots/metronome/playing.png
  src/screenshots/metronome/type2.png
  src/screenshots/splashScreen.png
  src/screenshots/volume/hover.png
  src/screenshots/volume/movedLeft.png
  src/screenshots/volume/movedRight.png
Labels: testing
